version: 0.2

phases:
    
  pre_build:
    commands:
      - docker build -t helloworld_build .
  build:
    commands:
      - docker images
      - docker run helloworld_build echo "Hello!!! GIooo"
      - docker save -o helloworld_build.tar helloworld_build

  post_build:
    commands:
      - echo "tutto apposto"
      
      
artifacts:
  files:
    - '**/*'
    
