version: 0.2

phases:
  install:
    runtime-versions:
      java: latest
      
  pre_build:
    commands:
      
  build:
    commands:
      - docker build -t dockertest .
      - docker run dockertest
      - docker save -o dockertest.tar dockertest

  post_build:
    commands:
      - echo "Sono in Post Build"
      
artifacts:
  files:
    - '**/*.tar'
      
