version: 0.2

phases:  

  pre_build:
    commands:
      - docker build -t dockertest .
      
  build:
    commands:
      - docker run dockertest
      - docker save -o dockertest.tar dockertest

  post_build:
    commands:
      - echo "Sono in Post Build"
      
artifacts:
  files:
    - '**/*.tar'
    - '/out/arpi-5.10/dist/Image.gz'
    - '/out/arpi-5.10/dist/bcm2711-rpi-4-b.dtb'
    - '/out/arpi-5.10/dist/bcm2711-rpi-400.dtb'
    - '/out/arpi-5.10/dist/vc4-kms-v3d-pi4.dtbo'
      
